# Generated by Django 6.1.1 on 2026-10-03 23:23

import django.db.models.deletion
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0003_tender_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pliego', 'Pliego'), ('anexo', 'Anexo'), ('especificaciones', 'Especificaciones técnicas'), ('circular_modificatoria', 'Circular modificatoria'), ('circular_aclaratoria', 'Circular aclaratoria'), ('respuesta_consulta', 'Respuesta a consulta')], max_length=30, verbose_name='tipo')),
                ('title', models.TextField(verbose_name='título')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='fecha del documento')),
                ('file_name', models.CharField(max_length=255, verbose_name='nombre del archivo')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'Página web')], max_length=10, verbose_name='formato')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='tamaño')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='huella del archivo')),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cargado')),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_documents_loaded', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
            ],
            options={
                'verbose_name': 'documento del pliego',
                'verbose_name_plural': 'documentos del pliego',
                'db_table': 'tenders_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='file', serialize=False, to='tenders.document', verbose_name='documento')),
                ('content', models.BinaryField(verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'archivo original del pliego',
                'verbose_name_plural': 'archivos originales del pliego',
                'db_table': 'tenders_document_file',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('read_document', 'Leer un documento'), ('propose_matrix', 'Proponer la matriz')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('queued', 'En espera'), ('running', 'En curso'), ('done', 'Terminado'), ('failed', 'Fallido')], default='queued', max_length=10, verbose_name='estado')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pedido')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='empezado')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='terminado')),
                ('error', models.TextField(blank=True, verbose_name='motivo de la falla')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='aviso visto')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='tenders.document', verbose_name='documento')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_jobs_requested', to=settings.AUTH_USER_MODEL, verbose_name='pedido por')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'tenders_job',
            },
        ),
        migrations.CreateModel(
            name='MatrixRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('media', 'Media'), ('alta', 'Alta'), ('exigente', 'Exigente')], max_length=10, verbose_name='nivel')),
                ('channel', models.CharField(choices=[('screen', 'Pantalla'), ('eval', 'Evaluación')], max_length=10, verbose_name='canal')),
                ('documents', models.JSONField(default=list, verbose_name='documentos')),
                ('authorization_date', models.DateField(verbose_name='fecha de autorización')),
                ('regime', models.JSONField(default=list, verbose_name='régimen')),
                ('corpus_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='versión de la normativa')),
                ('parameters', models.JSONField(default=dict, verbose_name='parámetros')),
                ('prompt_versions', models.JSONField(default=dict, verbose_name='versiones de instrucciones')),
                ('counts', models.JSONField(default=dict, verbose_name='cuentas')),
                ('timings', models.JSONField(default=dict, verbose_name='tiempos')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('models', models.JSONField(default=dict, verbose_name='modelos')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_runs', to='tenders.job', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'propuesta de matriz',
                'verbose_name_plural': 'propuestas de matriz',
                'db_table': 'tenders_matrix_run',
            },
        ),
        migrations.CreateModel(
            name='MatrixVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('validated', 'Validada'), ('discarded', 'Descartada')], default='draft', max_length=10, verbose_name='estado')),
                ('level', models.CharField(choices=[('media', 'Media'), ('alta', 'Alta'), ('exigente', 'Exigente')], max_length=10, verbose_name='nivel')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creada')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validada')),
                ('discarded_at', models.DateTimeField(blank=True, null=True, verbose_name='descartada')),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_versions', to='tenders.matrixversion', verbose_name='copiada de')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('discarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_versions_discarded', to=settings.AUTH_USER_MODEL, verbose_name='descartada por')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenders.matrixrun', verbose_name='propuesta')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_versions_validated', to=settings.AUTH_USER_MODEL, verbose_name='validada por')),
            ],
            options={
                'verbose_name': 'versión de la matriz',
                'verbose_name_plural': 'versiones de la matriz',
                'db_table': 'tenders_matrix_version',
            },
        ),
        migrations.AddField(
            model_name='matrixrun',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_run', to='tenders.matrixversion', verbose_name='versión creada'),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='número')),
                ('procedure_type', models.CharField(max_length=200, verbose_name='tipo')),
                ('subject', models.TextField(verbose_name='objeto')),
                ('authorization_date', models.DateField(verbose_name='fecha de autorización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures_created', to=settings.AUTH_USER_MODEL, verbose_name='dado de alta por')),
            ],
            options={
                'verbose_name': 'procedimiento',
                'verbose_name_plural': 'procedimientos',
                'db_table': 'tenders_procedure',
            },
        ),
        migrations.AddField(
            model_name='matrixversion',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_versions', to='tenders.procedure', verbose_name='procedimiento'),
        ),
        migrations.AddField(
            model_name='matrixrun',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_runs', to='tenders.procedure', verbose_name='procedimiento'),
        ),
        migrations.AddField(
            model_name='job',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='tenders.procedure', verbose_name='procedimiento'),
        ),
        migrations.AddField(
            model_name='document',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tenders.procedure', verbose_name='procedimiento'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='número de lectura')),
                ('pages', models.JSONField(verbose_name='lectura')),
                ('tables', models.JSONField(default=list, verbose_name='zonas de tabla')),
                ('canonical_text', models.TextField(verbose_name='texto canónico')),
                ('canonical_sha256', models.CharField(max_length=64, verbose_name='huella del texto canónico')),
                ('items', models.JSONField(default=list, verbose_name='renglones')),
                ('tool_versions', models.JSONField(verbose_name='versiones de las herramientas')),
                ('report', models.JSONField(verbose_name='informe')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='leída')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='tenders.document', verbose_name='documento')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='tenders.job', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'lectura del pliego',
                'verbose_name_plural': 'lecturas del pliego',
                'db_table': 'tenders_reading',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('category', models.CharField(choices=[('formal', 'Formal'), ('economico', 'Económico'), ('tecnico', 'Técnico')], max_length=20, verbose_name='clase')),
                ('items', models.JSONField(default=list, verbose_name='renglones')),
                ('origin', models.CharField(choices=[('propuesto', 'Propuesto por el sistema'), ('agregado', 'Agregado por una persona'), ('circular', 'Agregado por una circular')], max_length=20, verbose_name='origen')),
                ('state', models.CharField(choices=[('propuesto', 'Propuesto'), ('confirmado', 'Confirmado'), ('quitado', 'Quitado')], default='propuesto', max_length=20, verbose_name='estado')),
                ('proposed', models.JSONField(default=dict, verbose_name='propuesto')),
                ('passes', models.JSONField(default=list, verbose_name='pasadas')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='tenders.requirement', verbose_name='en la versión anterior')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='tenders.matrixversion', verbose_name='versión')),
            ],
            options={
                'verbose_name': 'requisito',
                'verbose_name_plural': 'requisitos',
                'db_table': 'tenders_requirement',
            },
        ),
        migrations.CreateModel(
            name='RequirementChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirmar', 'Confirmar'), ('corregir', 'Corregir'), ('quitar', 'Quitar'), ('restituir', 'Restituir'), ('agregar', 'Agregar'), ('elegir_consecuencia', 'Elegir la consecuencia')], max_length=20, verbose_name='acción')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='antes')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='después')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_changes', to='audit.auditevent', verbose_name='hecho registrado')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='tenders.requirement', verbose_name='requisito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_changes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'cambio de un requisito',
                'verbose_name_plural': 'cambios de requisitos',
                'db_table': 'tenders_requirement_change',
            },
        ),
        migrations.CreateModel(
            name='RequirementQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(verbose_name='texto literal')),
                ('scope', models.CharField(blank=True, choices=[('propia', 'Del renglón'), ('general', 'Común a todos los renglones')], max_length=10, verbose_name='alcance')),
                ('quote_flag', models.CharField(blank=True, choices=[('cita_amplia', 'Cita amplia, revisar')], max_length=20, verbose_name='marca')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='tenders.requirement', verbose_name='requisito')),
            ],
            options={
                'verbose_name': 'cita de un requisito',
                'verbose_name_plural': 'citas de requisitos',
                'db_table': 'tenders_requirement_quote',
            },
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(choices=[('extraccion', 'Extracción'), ('extraccion_2', 'Segunda extracción'), ('completitud', 'Completitud'), ('consecuencias', 'Consecuencias'), ('circulares', 'Circulares')], max_length=20, verbose_name='pasada')),
                ('batch', models.PositiveIntegerField(verbose_name='lote')),
                ('segment_keys', models.JSONField(default=list, verbose_name='claves de los tramos')),
                ('request', models.JSONField(verbose_name='pedido')),
                ('raw_output', models.TextField(blank=True, verbose_name='salida')),
                ('parsed', models.JSONField(blank=True, null=True, verbose_name='salida interpretada')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('timings', models.JSONField(default=dict, verbose_name='tiempos')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='tenders.runstep', verbose_name='reintento de')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='tenders.matrixrun', verbose_name='propuesta')),
            ],
            options={
                'verbose_name': 'pedido al modelo',
                'verbose_name_plural': 'pedidos al modelo',
                'db_table': 'tenders_run_step',
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='tenders.runstep', verbose_name='pedido al modelo'),
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence_type', models.CharField(choices=[('desestimacion', 'Desestimación sin posibilidad de subsanar'), ('intimacion_subsanar', 'Intimación a subsanar; si no se subsana, desestimación'), ('consultar_oferente', 'Consultar al oferente'), ('aprobacion_condicionada', 'Aprobación condicionada'), ('aprobar_igual', 'Aprobar de todas maneras'), ('otra_pliego', 'Otra consecuencia prevista en el pliego'), ('no_determinada', 'No determinada')], max_length=30, verbose_name='tipo')),
                ('grounds', models.JSONField(default=list, verbose_name='fundamentos')),
                ('origin', models.CharField(choices=[('sistema', 'Sistema'), ('persona', 'Persona')], max_length=10, verbose_name='origen')),
                ('chosen', models.BooleanField(default=False, verbose_name='elegida')),
                ('chosen_at', models.DateTimeField(blank=True, null=True, verbose_name='elegida el')),
                ('chosen_note', models.TextField(blank=True, verbose_name='motivo')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consequences_chosen', to=settings.AUTH_USER_MODEL, verbose_name='elegida por')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consequences', to='tenders.requirement', verbose_name='requisito')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consequences', to='tenders.runstep', verbose_name='pedido al modelo')),
            ],
            options={
                'verbose_name': 'consecuencia',
                'verbose_name_plural': 'consecuencias',
                'db_table': 'tenders_consequence',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('key', models.CharField(max_length=255, verbose_name='clave')),
                ('label', models.TextField(blank=True, verbose_name='encabezado')),
                ('path', models.TextField(blank=True, verbose_name='ruta')),
                ('segment_type', models.CharField(choices=[('titulo', 'Título'), ('clausula', 'Cláusula'), ('vineta', 'Viñeta o inciso'), ('parrafo', 'Párrafo'), ('tabla', 'Tabla'), ('pagina', 'Página sin texto legible'), ('no_ubicado', 'No ubicado')], max_length=20, verbose_name='tipo')),
                ('section_class', models.CharField(blank=True, choices=[('formal', 'Formal'), ('economico', 'Económico'), ('tecnico', 'Técnico')], max_length=20, verbose_name='clase de la sección')),
                ('items', models.JSONField(default=list, verbose_name='renglones')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='página inicial')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='página final')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(blank=True, verbose_name='texto literal')),
                ('text_origin', models.CharField(blank=True, choices=[('pdf_text', 'PDF con texto'), ('ocr', 'Reconocimiento de texto'), ('web', 'Página web')], max_length=10, verbose_name='origen del texto')),
                ('ocr_confidence_min', models.FloatField(blank=True, null=True, verbose_name='confianza mínima')),
                ('ocr_confidence_avg', models.FloatField(blank=True, null=True, verbose_name='confianza promedio')),
                ('review_reason', models.CharField(blank=True, choices=[('pagina_ilegible', 'Página ilegible'), ('pagina_dudosa', 'Página dudosa'), ('tabla', 'Tabla'), ('no_ubicado', 'Tramo no ubicado')], max_length=20, verbose_name='motivo de revisión')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='tenders.reading', verbose_name='lectura')),
            ],
            options={
                'verbose_name': 'tramo',
                'verbose_name_plural': 'tramos',
                'db_table': 'tenders_segment',
            },
        ),
        migrations.CreateModel(
            name='RequirementSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('modifica', 'Modifica'), ('aclara', 'Aclara'), ('suprime', 'Suprime')], max_length=10, verbose_name='efecto')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(verbose_name='texto literal')),
                ('issued_on', models.DateField(verbose_name='fecha del documento')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='tenders.requirementquote', verbose_name='cita alcanzada')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='tenders.requirement', verbose_name='requisito')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirement_sources', to='tenders.runstep', verbose_name='pedido al modelo')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_sources', to='tenders.segment', verbose_name='tramo de la circular')),
            ],
            options={
                'verbose_name': 'fuente de circular',
                'verbose_name_plural': 'fuentes de circulares',
                'db_table': 'tenders_requirement_source',
            },
        ),
        migrations.AddField(
            model_name='requirementquote',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='tenders.segment', verbose_name='tramo'),
        ),
        migrations.CreateModel(
            name='PendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('pagina_ilegible', 'Página ilegible'), ('pagina_dudosa', 'Página dudosa'), ('tabla', 'Tabla'), ('no_ubicado', 'Tramo no ubicado'), ('sin_disposicion', 'Sin disposición del modelo'), ('marcadores', 'Descartado con marcadores de obligación'), ('renglon_sin_especificaciones', 'Renglón sin especificaciones')], max_length=30, verbose_name='motivo')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelto')),
                ('resolution', models.CharField(blank=True, choices=[('sin_requisitos', 'Revisado, sin requisitos'), ('requisito_agregado', 'Requisito agregado')], max_length=20, verbose_name='resolución')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_items_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resuelto por')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_items', to='tenders.matrixversion', verbose_name='versión')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_items', to='tenders.segment', verbose_name='tramo')),
            ],
            options={
                'verbose_name': 'pendiente de revisión',
                'verbose_name_plural': 'pendientes de revisión',
                'db_table': 'tenders_pending_item',
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('requisitos', 'Con requisitos'), ('tecnico', 'Fila técnica'), ('descartado', 'Descartado'), ('pendiente', 'Pendiente de revisión')], max_length=20, verbose_name='disposición')),
                ('discard_reason', models.CharField(blank=True, choices=[('titulo', 'Título'), ('dato_procedimiento', 'Definición o dato del procedimiento'), ('norma_aplicable', 'Norma aplicable'), ('obligacion_organismo', 'Obligación del organismo que la oferta no puede contradecir ni condicionar'), ('ejecucion_contrato', 'Obligación de la ejecución del contrato'), ('formulario', 'Formulario a completar'), ('indice_caratula', 'Índice o carátula')], max_length=30, verbose_name='motivo de descarte')),
                ('source', models.CharField(choices=[('modelo', 'Modelo'), ('regla', 'Regla')], max_length=10, verbose_name='origen')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='tenders.matrixrun', verbose_name='propuesta')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='tenders.runstep', verbose_name='pedido al modelo')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='tenders.segment', verbose_name='tramo')),
            ],
            options={
                'verbose_name': 'disposición de un tramo',
                'verbose_name_plural': 'disposiciones de tramos',
                'db_table': 'tenders_disposition',
            },
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'validated', 'discarded'])), name='tenders_matrix_version_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['media', 'alta', 'exigente'])), name='tenders_matrix_version_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.UniqueConstraint(fields=('procedure', 'number'), name='tenders_matrix_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('procedure',), name='tenders_matrix_version_one_draft'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'validated'), _negated=True), models.Q(('validated_at__isnull', False), ('validated_by__isnull', False)), _connector='OR'), name='tenders_matrix_version_validated_has_who_when'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'discarded'), _negated=True), models.Q(('discarded_at__isnull', False), ('discarded_by__isnull', False)), _connector='OR'), name='tenders_matrix_version_discarded_has_who_when'),
        ),
        migrations.AddConstraint(
            model_name='matrixrun',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['media', 'alta', 'exigente'])), name='tenders_matrix_run_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixrun',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['screen', 'eval'])), name='tenders_matrix_run_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['read_document', 'propose_matrix'])), name='tenders_job_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'done', 'failed'])), name='tenders_job_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'read_document'), _negated=True), ('document__isnull', False), _connector='OR'), name='tenders_job_read_document_has_document'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['pliego', 'anexo', 'especificaciones', 'circular_modificatoria', 'circular_aclaratoria', 'respuesta_consulta'])), name='tenders_document_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_format__in', ['pdf', 'html'])), name='tenders_document_file_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_sha256__regex', '^[0-9a-f]{64}$')), name='tenders_document_file_sha256_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('procedure', 'file_sha256'), name='tenders_document_sha256_unique_in_procedure'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('circular_modificatoria', 'circular_aclaratoria', 'respuesta_consulta')), _negated=True), ('issued_on__isnull', False), _connector='OR'), name='tenders_document_dated_kinds_have_date'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='tenders_reading_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('items'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_reading_items_is_list'),
        ),
        migrations.AddConstraint(
            model_name='requirementchange',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['confirmar', 'corregir', 'quitar', 'restituir', 'agregar', 'elegir_consecuencia'])), name='tenders_requirement_change_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='runstep',
            constraint=models.CheckConstraint(condition=models.Q(('pass_name__in', ['extraccion', 'extraccion_2', 'completitud', 'consecuencias', 'circulares'])), name='tenders_run_step_pass_name_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['formal', 'economico', 'tecnico'])), name='tenders_requirement_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['propuesto', 'agregado', 'circular'])), name='tenders_requirement_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['propuesto', 'confirmado', 'quitado'])), name='tenders_requirement_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('items'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_requirement_items_is_list'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'tecnico'), _negated=True), django.db.models.lookups.LessThanOrEqual(models.Func(models.F('items'), function='jsonb_array_length', output_field=models.IntegerField()), 1), _connector='OR'), name='tenders_requirement_technical_one_item'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('version', 'number'), name='tenders_requirement_number_unique_in_version'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.CheckConstraint(condition=models.Q(('consequence_type__in', ['desestimacion', 'intimacion_subsanar', 'consultar_oferente', 'aprobacion_condicionada', 'aprobar_igual', 'otra_pliego', 'no_determinada'])), name='tenders_consequence_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['sistema', 'persona'])), name='tenders_consequence_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('grounds'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_consequence_grounds_is_list'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.CheckConstraint(condition=models.Q(('consequence_type__in', ('aprobacion_condicionada', 'aprobar_igual')), ('origin', 'sistema'), _negated=True), name='tenders_consequence_evaluator_only_types'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consequence_type', 'no_determinada'), _negated=True), models.Q(('chosen', False), ('origin', 'sistema')), _connector='OR'), name='tenders_consequence_undetermined_not_chosen'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.CheckConstraint(condition=models.Q(('chosen', False), models.Q(('chosen_at__isnull', False), ('chosen_by__isnull', False)), _connector='OR'), name='tenders_consequence_chosen_has_who_when'),
        ),
        migrations.AddConstraint(
            model_name='consequence',
            constraint=models.UniqueConstraint(condition=models.Q(('chosen', True)), fields=('requirement',), name='tenders_consequence_one_chosen'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(('segment_type__in', ['titulo', 'clausula', 'vineta', 'parrafo', 'tabla', 'pagina', 'no_ubicado'])), name='tenders_segment_segment_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(('section_class__in', ['formal', 'economico', 'tecnico']), ('section_class', ''), _connector='OR'), name='tenders_segment_section_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(('text_origin__in', ['pdf_text', 'ocr', 'web']), ('text_origin', ''), _connector='OR'), name='tenders_segment_text_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(('review_reason__in', ['pagina_ilegible', 'pagina_dudosa', 'tabla', 'no_ubicado']), ('review_reason', ''), _connector='OR'), name='tenders_segment_review_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('items'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_segment_items_is_list'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='tenders_segment_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('reading', 'key'), name='tenders_segment_key_unique_in_reading'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('reading', 'order'), name='tenders_segment_order_unique_in_reading'),
        ),
        migrations.AddConstraint(
            model_name='requirementsource',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['modifica', 'aclara', 'suprime'])), name='tenders_requirement_source_effect_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementsource',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='tenders_requirement_source_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementquote',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['propia', 'general']), ('scope', ''), _connector='OR'), name='tenders_requirement_quote_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementquote',
            constraint=models.CheckConstraint(condition=models.Q(('quote_flag__in', ['cita_amplia']), ('quote_flag', ''), _connector='OR'), name='tenders_requirement_quote_flag_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementquote',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='tenders_requirement_quote_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementquote',
            constraint=models.UniqueConstraint(fields=('requirement', 'order'), name='tenders_requirement_quote_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='pendingitem',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['pagina_ilegible', 'pagina_dudosa', 'tabla', 'no_ubicado', 'sin_disposicion', 'marcadores', 'renglon_sin_especificaciones'])), name='tenders_pending_item_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='pendingitem',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ['sin_requisitos', 'requisito_agregado']), ('resolution', ''), _connector='OR'), name='tenders_pending_item_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='pendingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', ''), ('resolved_at__isnull', True), ('resolved_by__isnull', True)), models.Q(models.Q(('resolution', ''), _negated=True), ('resolved_at__isnull', False), ('resolved_by__isnull', False)), _connector='OR'), name='tenders_pending_item_resolution_has_who_when'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['requisitos', 'tecnico', 'descartado', 'pendiente'])), name='tenders_disposition_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(('discard_reason__in', ['titulo', 'dato_procedimiento', 'norma_aplicable', 'obligacion_organismo', 'ejecucion_contrato', 'formulario', 'indice_caratula']), ('discard_reason', ''), _connector='OR'), name='tenders_disposition_discard_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['modelo', 'regla'])), name='tenders_disposition_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'descartado'), _negated=True), models.Q(('discard_reason', ''), _negated=True), _connector='OR'), name='tenders_disposition_discard_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.UniqueConstraint(fields=('run', 'segment'), name='tenders_disposition_one_per_segment'),
        ),
    ]
