"""T-099 (plan 003, enmienda del 2026-10-04, REQ-030, REQ-033, REQ-035, REQ-036): filas
descartadas, sugerencias, respaldo normativo, citas repetidas y proceso único.

Además del esquema que genera Django, dos reglas de la base:

1. **Solo inserción** (P6): `tenders_discarded_row` y `tenders_norm_support` rechazan
   todo UPDATE y DELETE, con la función `tenders_reject_change()` de la migración 0002.
2. **La cita principal** (REQ-025): una cita `repetida` no cuenta como la cita de un
   formal o económico. Los triggers de la 0002 cuentan citas con
   `tenders_quote_count()`; pasa a contar solo las que no son `repetida`, así un formal
   o económico tiene exactamente una cita principal y las `repetida` que haga falta. Un
   técnico no cambia.
"""

# Generated by Django 6.1.1 on 2026-10-04 18:44

import django.db.models.deletion
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


FORWARD = r"""
CREATE TRIGGER tenders_discarded_row_append_only
    BEFORE UPDATE OR DELETE ON tenders_discarded_row
    FOR EACH ROW EXECUTE FUNCTION tenders_reject_change();

CREATE TRIGGER tenders_norm_support_append_only
    BEFORE UPDATE OR DELETE ON tenders_norm_support
    FOR EACH ROW EXECUTE FUNCTION tenders_reject_change();

CREATE OR REPLACE FUNCTION tenders_quote_count(requirement bigint) RETURNS bigint
LANGUAGE sql STABLE AS $$
    SELECT count(*) FROM tenders_requirement_quote q
    WHERE q.requirement_id = requirement AND q.scope <> 'repetida'
$$;
"""

REVERSE = r"""
CREATE OR REPLACE FUNCTION tenders_quote_count(requirement bigint) RETURNS bigint
LANGUAGE sql STABLE AS $$
    SELECT count(*) FROM tenders_requirement_quote q WHERE q.requirement_id = requirement
$$;

DROP TRIGGER tenders_norm_support_append_only ON tenders_norm_support;
DROP TRIGGER tenders_discarded_row_append_only ON tenders_discarded_row;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_user_role_changed'),
        ('norms', '0007_norm_citation'),
        ('tenders', '0002_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden en el pliego')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(verbose_name='texto literal')),
                ('extra_quotes', models.JSONField(default=list, verbose_name='citas adicionales')),
                ('category', models.CharField(choices=[('formal', 'Formal'), ('economico', 'Económico'), ('tecnico', 'Técnico')], max_length=20, verbose_name='clase')),
                ('items', models.JSONField(default=list, verbose_name='renglones')),
                ('reason', models.CharField(choices=[('titulo', 'Título'), ('dato_procedimiento', 'Definición o dato del procedimiento'), ('norma_aplicable', 'Norma aplicable'), ('obligacion_organismo', 'Obligación del organismo'), ('ejecucion_contrato', 'Obligación de la ejecución del contrato'), ('formulario', 'Formulario a completar'), ('indice_caratula', 'Índice o carátula'), ('consecuencia_sancion', 'Consecuencia o sanción'), ('derecho_posterior', 'Derecho posterior a la oferta')], max_length=30, verbose_name='motivo')),
                ('evidence_start', models.PositiveIntegerField(verbose_name='inicio del indicio')),
                ('evidence_end', models.PositiveIntegerField(verbose_name='fin del indicio')),
                ('evidence_text', models.TextField(verbose_name='indicio literal')),
                ('vote_a', models.JSONField(verbose_name='respuesta A')),
                ('vote_b', models.JSONField(verbose_name='respuesta B')),
                ('source_pass', models.CharField(max_length=20, verbose_name='pasada que la propuso')),
                ('passes', models.JSONField(default=list, verbose_name='pasadas que la encontraron')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
            ],
            options={
                'verbose_name': 'fila descartada por el sistema',
                'verbose_name_plural': 'filas descartadas por el sistema',
                'db_table': 'tenders_discarded_row',
            },
        ),
        migrations.CreateModel(
            name='NormSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(max_length=500, verbose_name='norma y ruta')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en la unidad')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en la unidad')),
                ('text', models.TextField(verbose_name='cita literal')),
                ('score', models.FloatField(verbose_name='puntaje del reranker')),
                ('regime', models.CharField(max_length=200, verbose_name='régimen')),
                ('corpus_version', models.PositiveIntegerField(verbose_name='versión de la normativa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
            ],
            options={
                'verbose_name': 'respaldo normativo',
                'verbose_name_plural': 'respaldos normativos',
                'db_table': 'tenders_norm_support',
            },
        ),
        migrations.RemoveConstraint(
            model_name='disposition',
            name='tenders_disposition_source_valid',
        ),
        migrations.RemoveConstraint(
            model_name='matrixrun',
            name='tenders_matrix_run_level_valid',
        ),
        migrations.RemoveConstraint(
            model_name='matrixversion',
            name='tenders_matrix_version_level_valid',
        ),
        migrations.RemoveConstraint(
            model_name='requirement',
            name='tenders_requirement_origin_valid',
        ),
        migrations.RemoveConstraint(
            model_name='requirement',
            name='tenders_requirement_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='requirementchange',
            name='tenders_requirement_change_action_valid',
        ),
        migrations.RemoveConstraint(
            model_name='requirementquote',
            name='tenders_requirement_quote_scope_valid',
        ),
        migrations.RemoveConstraint(
            model_name='runstep',
            name='tenders_run_step_pass_name_valid',
        ),
        migrations.AddField(
            model_name='matrixrun',
            name='process',
            field=models.CharField(blank=True, choices=[('completo', 'Completo')], max_length=10, verbose_name='proceso'),
        ),
        migrations.AddField(
            model_name='matrixversion',
            name='process',
            field=models.CharField(blank=True, choices=[('completo', 'Completo')], max_length=10, verbose_name='proceso'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='doubt',
            field=models.JSONField(default=dict, verbose_name='duda'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='doubt_reason',
            field=models.CharField(blank=True, choices=[('no_coinciden', 'Las dos respuestas no coinciden'), ('duda', 'El modelo dudó'), ('descarte_sin_sustento', 'Descarte sin indicio verificable'), ('opinion_incompleta', 'Opinión incompleta')], max_length=30, verbose_name='motivo de la duda'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='source',
            field=models.CharField(choices=[('modelo', 'Modelo'), ('regla', 'Regla'), ('filtro', 'Filtro')], max_length=10, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='matrixrun',
            name='level',
            field=models.CharField(blank=True, choices=[('media', 'Media'), ('alta', 'Alta'), ('exigente', 'Exigente')], max_length=10, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='matrixversion',
            name='level',
            field=models.CharField(blank=True, choices=[('media', 'Media'), ('alta', 'Alta'), ('exigente', 'Exigente')], max_length=10, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='origin',
            field=models.CharField(choices=[('propuesto', 'Propuesto por el sistema'), ('agregado', 'Agregado por una persona'), ('circular', 'Agregado por una circular'), ('devuelto', 'Devuelto de las descartadas')], max_length=20, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='state',
            field=models.CharField(choices=[('propuesto', 'Propuesto'), ('confirmado', 'Confirmado'), ('quitado', 'Quitado'), ('sugerido', 'Sugerido')], default='propuesto', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='requirementchange',
            name='action',
            field=models.CharField(choices=[('confirmar', 'Confirmar'), ('corregir', 'Corregir'), ('quitar', 'Quitar'), ('restituir', 'Restituir'), ('agregar', 'Agregar'), ('elegir_consecuencia', 'Elegir la consecuencia'), ('devolver', 'Devolver de las descartadas'), ('aceptar_sugerencia', 'Pasar una sugerencia a requisito')], max_length=20, verbose_name='acción'),
        ),
        migrations.AlterField(
            model_name='requirementquote',
            name='scope',
            field=models.CharField(blank=True, choices=[('propia', 'Del renglón'), ('general', 'Común a todos los renglones'), ('repetida', 'Cita adicional de la misma condición')], max_length=10, verbose_name='alcance'),
        ),
        migrations.AlterField(
            model_name='runstep',
            name='pass_name',
            field=models.CharField(choices=[('extraccion', 'Extracción'), ('extraccion_2', 'Segunda extracción'), ('completitud', 'Completitud'), ('consecuencias', 'Consecuencias'), ('circulares', 'Circulares'), ('unificacion', 'Unificación de repetidas'), ('filtro', 'Filtro de sobrantes'), ('filtro_2', 'Filtro de sobrantes, segunda opinión'), ('respaldo_normativo', 'Respaldo normativo')], max_length=20, verbose_name='pasada'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['modelo', 'regla', 'filtro'])), name='tenders_disposition_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixrun',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['media', 'alta', 'exigente']), ('level', ''), _connector='OR'), name='tenders_matrix_run_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixrun',
            constraint=models.CheckConstraint(condition=models.Q(('process__in', ['completo']), ('process', ''), _connector='OR'), name='tenders_matrix_run_process_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['media', 'alta', 'exigente']), ('level', ''), _connector='OR'), name='tenders_matrix_version_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='matrixversion',
            constraint=models.CheckConstraint(condition=models.Q(('process__in', ['completo']), ('process', ''), _connector='OR'), name='tenders_matrix_version_process_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementchange',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['confirmar', 'corregir', 'quitar', 'restituir', 'agregar', 'elegir_consecuencia', 'devolver', 'aceptar_sugerencia'])), name='tenders_requirement_change_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirementquote',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['propia', 'general', 'repetida']), ('scope', ''), _connector='OR'), name='tenders_requirement_quote_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='runstep',
            constraint=models.CheckConstraint(condition=models.Q(('pass_name__in', ['extraccion', 'extraccion_2', 'completitud', 'consecuencias', 'circulares', 'unificacion', 'filtro', 'filtro_2', 'respaldo_normativo'])), name='tenders_run_step_pass_name_valid'),
        ),
        migrations.AddField(
            model_name='discardedrow',
            name='evidence_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenders.segment', verbose_name='tramo del indicio'),
        ),
        migrations.AddField(
            model_name='discardedrow',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discarded_rows', to='tenders.matrixrun', verbose_name='propuesta'),
        ),
        migrations.AddField(
            model_name='discardedrow',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discarded_rows', to='tenders.segment', verbose_name='tramo'),
        ),
        migrations.AddField(
            model_name='discardedrow',
            name='step_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenders.runstep', verbose_name='pedido A'),
        ),
        migrations.AddField(
            model_name='discardedrow',
            name='step_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenders.runstep', verbose_name='pedido B'),
        ),
        migrations.AddField(
            model_name='discardedrow',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discarded_rows', to='tenders.matrixversion', verbose_name='versión'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='restored_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restored_requirements', to='tenders.discardedrow', verbose_name='devuelto de'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['propuesto', 'agregado', 'circular', 'devuelto'])), name='tenders_requirement_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['propuesto', 'confirmado', 'quitado', 'sugerido'])), name='tenders_requirement_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(('doubt_reason__in', ['no_coinciden', 'duda', 'descarte_sin_sustento', 'opinion_incompleta']), ('doubt_reason', ''), _connector='OR'), name='tenders_requirement_doubt_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'sugerido'), _negated=True), models.Q(models.Q(('doubt_reason', ''), _negated=True), models.Q(('category', 'tecnico'), _negated=True)), _connector='OR'), name='tenders_requirement_suggestion_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('restored_from__isnull', False)), fields=('version', 'restored_from'), name='tenders_requirement_restored_from_unique_in_version'),
        ),
        migrations.AddField(
            model_name='normsupport',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norm_supports', to='tenders.requirement', verbose_name='requisito'),
        ),
        migrations.AddField(
            model_name='normsupport',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norm_supports', to='tenders.runstep', verbose_name='pedido al modelo'),
        ),
        migrations.AddField(
            model_name='normsupport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='norms.unit', verbose_name='unidad de la norma'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['formal', 'economico'])), name='tenders_discarded_row_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['titulo', 'dato_procedimiento', 'norma_aplicable', 'obligacion_organismo', 'ejecucion_contrato', 'formulario', 'indice_caratula', 'consecuencia_sancion', 'derecho_posterior'])), name='tenders_discarded_row_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(('source_pass__in', ['extraccion', 'extraccion_2', 'completitud', 'consecuencias', 'circulares', 'unificacion', 'filtro', 'filtro_2', 'respaldo_normativo'])), name='tenders_discarded_row_source_pass_valid'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('items'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_discarded_row_items_is_list'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('extra_quotes'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_discarded_row_extra_quotes_is_list'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func(models.F('passes'), function='jsonb_typeof', output_field=models.TextField()), 'array')), name='tenders_discarded_row_passes_is_list'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='tenders_discarded_row_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='discardedrow',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_end__gte', models.F('evidence_start'))), name='tenders_discarded_row_evidence_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='normsupport',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='tenders_norm_support_char_range_valid'),
        ),
        migrations.RunSQL(sql=FORWARD, reverse_sql=REVERSE),
    ]
