# Generated by Django 6.1.1 on 2026-10-05 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_circulares_original_y_cambios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='tenders_job_kind_valid',
        ),
        migrations.AddField(
            model_name='job',
            name='target_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='objeto del pedido'),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('read_document', 'Leer un documento'), ('propose_matrix', 'Proponer la matriz'), ('read_offer_document', 'Leer un documento de una oferta'), ('build_sheet', 'Armar la ficha de una oferta')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['read_document', 'propose_matrix', 'read_offer_document', 'build_sheet'])), name='tenders_job_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['read_offer_document', 'build_sheet']), _negated=True), ('target_id__isnull', False), _connector='OR'), name='tenders_job_offer_kinds_have_target'),
        ),
    ]
