# Generated by Django 6.1.1 on 2026-10-05 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_ofertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='tenders_job_kind_valid',
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('read_document', 'Leer un documento'), ('propose_matrix', 'Proponer la matriz'), ('read_offer_document', 'Leer un documento de una oferta'), ('build_sheet', 'Armar la ficha de una oferta'), ('portal_explore', 'Explorar un proceso del Portal'), ('portal_review', 'Revisar un proceso del Portal')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='tenders.procedure', verbose_name='procedimiento'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['read_document', 'propose_matrix', 'read_offer_document', 'build_sheet', 'portal_explore', 'portal_review'])), name='tenders_job_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('procedure__isnull', False), ('kind__in', ('portal_explore', 'portal_review')), _connector='OR'), name='tenders_job_procedure_required'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('portal_explore', 'portal_review')), _negated=True), ('target_id__isnull', False), _connector='OR'), name='tenders_job_portal_kinds_have_target'),
        ),
    ]
