# Generated by Django 6.1.1 on 2026-10-06 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='tenders_job_kind_valid',
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('read_document', 'Leer un documento'), ('propose_matrix', 'Proponer la matriz'), ('read_offer_document', 'Leer un documento de una oferta'), ('build_sheet', 'Armar la ficha de una oferta'), ('portal_explore', 'Explorar un proceso del Portal'), ('portal_review', 'Revisar un proceso del Portal'), ('evaluate_offers', 'Evaluar las ofertas')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['read_document', 'propose_matrix', 'read_offer_document', 'build_sheet', 'portal_explore', 'portal_review', 'evaluate_offers'])), name='tenders_job_kind_valid'),
        ),
    ]
