# Generated by Django 6.1.1 on 2026-10-03 01:16

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='momento')),
                ('event_type', models.CharField(choices=[('load', 'Carga'), ('reread', 'Relectura'), ('validation', 'Validación'), ('relation', 'Relación'), ('version', 'Versión'), ('pending_amendment', 'Modificatorias sin cargar'), ('query', 'Consulta'), ('search', 'Búsqueda'), ('login', 'Ingreso'), ('login_failed', 'Ingreso fallido'), ('rejected', 'Operación rechazada por rol'), ('user_created', 'Alta de usuario')], max_length=20, verbose_name='hecho')),
                ('outcome', models.CharField(choices=[('ok', 'Hecho'), ('rejected', 'Rechazado'), ('failed', 'Fallido')], max_length=10, verbose_name='resultado')),
                ('channel', models.CharField(choices=[('screen', 'Pantalla'), ('command', 'Comando'), ('eval', 'Evaluación')], max_length=10, verbose_name='canal')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='nombre escrito')),
                ('corpus_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='versión de la normativa')),
                ('detail', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='detalle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'hecho registrado',
                'verbose_name_plural': 'hechos registrados',
                'db_table': 'audit_event',
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['load', 'reread', 'validation', 'relation', 'version', 'pending_amendment', 'query', 'search', 'login', 'login_failed', 'rejected', 'user_created'])), name='audit_event_event_type_valid'), models.CheckConstraint(condition=models.Q(('outcome__in', ['ok', 'rejected', 'failed'])), name='audit_event_outcome_valid'), models.CheckConstraint(condition=models.Q(('channel__in', ['screen', 'command', 'eval'])), name='audit_event_channel_valid')],
            },
        ),
    ]
