# Generated by Django 6.1.1 on 2026-10-06 04:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0007_evaluacion'),
        ('norms', '0007_norm_citation'),
        ('offers', '0003_docx_format'),
        ('tenders', '0007_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirmar', 'Confirmar'), ('corregir', 'Corregir'), ('rechazar', 'Rechazar'), ('pedir_subsanacion', 'Pedir la subsanación'), ('subsanar', 'Documento agregado por subsanación')], max_length=20, verbose_name='acción')),
                ('outcome_after', models.CharField(blank=True, choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('sin_documento', 'No se encontró el documento'), ('no_determinado', 'No determinado')], max_length=20, verbose_name='resultado después')),
                ('note', models.TextField(blank=True, verbose_name='nota')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_decisions', to='offers.document', verbose_name='documento agregado')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_decisions', to='audit.auditevent', verbose_name='hecho registrado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_decisions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'decisión sobre un resultado',
                'verbose_name_plural': 'decisiones sobre los resultados',
                'db_table': 'assessment_decision',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='pregunta')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='motivo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='formulada')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='offers.offer', verbose_name='oferta')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='tenders.procedure', verbose_name='procedimiento')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='tenders.requirement', verbose_name='requisito')),
            ],
            options={
                'verbose_name': 'pregunta a la Comisión',
                'verbose_name_plural': 'preguntas a la Comisión',
                'db_table': 'assessment_question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='respuesta')),
                ('scope', models.CharField(choices=[('par', 'Solo esa oferta y ese requisito'), ('requisito', 'Todas las ofertas de ese requisito'), ('procedimiento', 'Todo el procedimiento')], default='requisito', max_length=15, verbose_name='alcance')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='respondida')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_answers', to=settings.AUTH_USER_MODEL, verbose_name='respondida por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_answers', to='audit.auditevent', verbose_name='hecho registrado')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessment.question', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'respuesta de la Comisión',
                'verbose_name_plural': 'respuestas de la Comisión',
                'db_table': 'assessment_answer',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.JSONField(verbose_name='ofertas')),
                ('requirements', models.JSONField(blank=True, null=True, verbose_name='requisitos')),
                ('cause', models.CharField(choices=[('matriz', 'Evaluación de la matriz'), ('subsanacion', 'Subsanación'), ('respuesta', 'Respuesta de la Comisión'), ('nueva_version', 'Nueva versión de la matriz'), ('manual', 'A mano')], max_length=15, verbose_name='causa')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pedida')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='assessment.answer', verbose_name='respuesta de origen')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='assessment.decision', verbose_name='decisión de origen')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_requests', to='tenders.job', verbose_name='pedido de la cola')),
                ('matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_requests', to='tenders.matrixversion', verbose_name='versión de la matriz')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_requests', to='tenders.procedure', verbose_name='procedimiento')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_requests', to=settings.AUTH_USER_MODEL, verbose_name='pedida por')),
            ],
            options={
                'verbose_name': 'pedido de evaluación',
                'verbose_name_plural': 'pedidos de evaluación',
                'db_table': 'assessment_request',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('sin_documento', 'No se encontró el documento'), ('no_determinado', 'No determinado')], max_length=20, verbose_name='resultado')),
                ('doubt', models.CharField(blank=True, choices=[('duda', 'Duda'), ('sin_corroborar', 'Sin corroborar'), ('contradiccion', 'Contradicción entre documentos'), ('lectura_incompleta', 'Lectura incompleta'), ('externo', 'Requisito que se verifica fuera de la oferta'), ('sin_cita', 'Sin cita ubicada'), ('sin_dato', 'Falta un dato')], max_length=20, verbose_name='motivo de la duda')),
                ('exigence', models.CharField(blank=True, choices=[('documento', 'Documento'), ('condicion', 'Condición')], max_length=10, verbose_name='exigencia')),
                ('explanation', models.TextField(blank=True, verbose_name='explicación')),
                ('unread_pages_warning', models.BooleanField(default=False, verbose_name='hay páginas sin leer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='offers.offer', verbose_name='oferta')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_results', to='assessment.result', verbose_name='resultado anterior')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='tenders.requirement', verbose_name='requisito')),
            ],
            options={
                'verbose_name': 'resultado propuesto',
                'verbose_name_plural': 'resultados propuestos',
                'db_table': 'assessment_result',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessment.result', verbose_name='resultado de origen'),
        ),
        migrations.AddField(
            model_name='decision',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='assessment.result', verbose_name='resultado'),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('kind', models.CharField(choices=[('oferta', 'Texto de la oferta'), ('pliego', 'Texto del pliego'), ('norma', 'Norma'), ('respuesta', 'Respuesta de la Comisión')], max_length=10, verbose_name='clase')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='página')),
                ('char_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='fin en el texto canónico')),
                ('text', models.TextField(blank=True, verbose_name='texto literal')),
                ('original_text', models.TextField(blank=True, verbose_name='texto original')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='norma y artículo')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='assessment.answer', verbose_name='respuesta')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_citations', to='offers.document', verbose_name='documento')),
                ('norm_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_citations', to='norms.unit', verbose_name='unidad de la normativa')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_citations', to='offers.reading', verbose_name='lectura')),
                ('requirement_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_citations', to='tenders.requirementquote', verbose_name='cita del requisito')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='assessment.result', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'fundamento de un resultado',
                'verbose_name_plural': 'fundamentos de los resultados',
                'db_table': 'assessment_citation',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('channel', models.CharField(choices=[('screen', 'Pantalla'), ('eval', 'Evaluación')], max_length=10, verbose_name='canal')),
                ('documents', models.JSONField(verbose_name='documentos')),
                ('norms', models.JSONField(verbose_name='normativa')),
                ('models_used', models.JSONField(db_column='models', verbose_name='modelos')),
                ('parameters', models.JSONField(verbose_name='parámetros')),
                ('prompt_versions', models.JSONField(verbose_name='versiones de las instrucciones')),
                ('counts', models.JSONField(default=dict, verbose_name='cuentas')),
                ('timings', models.JSONField(default=dict, verbose_name='tiempos')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('built_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='armada')),
                ('matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_runs', to='tenders.matrixversion', verbose_name='versión de la matriz')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_runs', to='offers.offer', verbose_name='oferta')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='assessment.request', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'evaluación de una oferta',
                'verbose_name_plural': 'evaluaciones de ofertas',
                'db_table': 'assessment_run',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessment.run', verbose_name='evaluación'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('grupo', 'Lectura de un grupo de documentos'), ('contraste', 'Contraste'), ('reescritura', 'Reescritura del requisito')], max_length=15, verbose_name='para qué')),
                ('group_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='grupo')),
                ('documents', models.JSONField(default=list, verbose_name='documentos o ventanas')),
                ('request', models.JSONField(blank=True, null=True, verbose_name='pedido')),
                ('raw_output', models.TextField(blank=True, verbose_name='salida cruda')),
                ('parsed', models.JSONField(blank=True, null=True, verbose_name='interpretado')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens del pedido')),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de la salida')),
                ('timings', models.JSONField(default=dict, verbose_name='tiempos')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_steps', to='offers.offer', verbose_name='oferta')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_steps', to='tenders.requirement', verbose_name='requisito')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='assessment.step', verbose_name='reintento de')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='assessment.run', verbose_name='evaluación')),
            ],
            options={
                'verbose_name': 'pedido al modelo de la evaluación',
                'verbose_name_plural': 'pedidos al modelo de la evaluación',
                'db_table': 'assessment_step',
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['par', 'requisito', 'procedimiento'])), name='assessment_answer_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='assessment_answer_text_required'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('cause__in', ['matriz', 'subsanacion', 'respuesta', 'nueva_version', 'manual'])), name='assessment_request_cause_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='assessment_question_text_required'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['confirmar', 'corregir', 'rechazar', 'pedir_subsanacion', 'subsanar'])), name='assessment_decision_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('outcome_after__in', ['cumple', 'no_cumple', 'sin_documento', 'no_determinado']), ('outcome_after', ''), _connector='OR'), name='assessment_decision_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ('corregir', 'rechazar', 'pedir_subsanacion')), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='assessment_decision_note_required'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'corregir'), models.Q(('outcome_after', ''), _negated=True)), models.Q(models.Q(('action', 'corregir'), _negated=True), ('outcome_after', '')), _connector='OR'), name='assessment_decision_outcome_after_only_if_corrected'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'subsanar'), ('document__isnull', False)), models.Q(models.Q(('action', 'subsanar'), _negated=True), ('document__isnull', True)), _connector='OR'), name='assessment_decision_document_only_if_remedied'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['oferta', 'pliego', 'norma', 'respuesta'])), name='assessment_citation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(fields=('result', 'order'), name='assessment_citation_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'oferta'), _negated=True), models.Q(('kind', 'oferta'), ('document__isnull', False), ('reading__isnull', False), ('page__isnull', False), ('char_start__isnull', False), ('char_end__isnull', False), ('requirement_quote__isnull', True), ('norm_unit__isnull', True), ('answer__isnull', True), ('char_end__gte', models.F('char_start')), models.Q(('text', ''), _negated=True)), _connector='OR'), name='assessment_citation_oferta_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'pliego'), _negated=True), models.Q(('kind', 'pliego'), ('requirement_quote__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('norm_unit__isnull', True), ('answer__isnull', True), models.Q(('text', ''), _negated=True)), _connector='OR'), name='assessment_citation_pliego_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'norma'), _negated=True), models.Q(('kind', 'norma'), ('norm_unit__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('requirement_quote__isnull', True), ('answer__isnull', True), models.Q(('text', ''), _negated=True), models.Q(('label', ''), _negated=True)), _connector='OR'), name='assessment_citation_norma_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'respuesta'), _negated=True), models.Q(('kind', 'respuesta'), ('answer__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('requirement_quote__isnull', True), ('norm_unit__isnull', True)), _connector='OR'), name='assessment_citation_respuesta_fields'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['screen', 'eval'])), name='assessment_run_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('offer', 'number'), name='assessment_run_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['cumple', 'no_cumple', 'sin_documento', 'no_determinado'])), name='assessment_result_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('doubt__in', ['duda', 'sin_corroborar', 'contradiccion', 'lectura_incompleta', 'externo', 'sin_cita', 'sin_dato']), ('doubt', ''), _connector='OR'), name='assessment_result_doubt_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('exigence__in', ['documento', 'condicion']), ('exigence', ''), _connector='OR'), name='assessment_result_exigence_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'no_determinado'), models.Q(('doubt', ''), _negated=True)), models.Q(models.Q(('outcome', 'no_determinado'), _negated=True), ('doubt', '')), _connector='OR'), name='assessment_result_doubt_only_if_undetermined'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('run', 'requirement'), name='assessment_result_requirement_unique'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['grupo', 'contraste', 'reescritura'])), name='assessment_step_purpose_valid'),
        ),
    ]
