# Generated by Django 6.1.1 on 2026-10-06 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_triggers'),
        ('audit', '0007_evaluacion'),
        ('norms', '0007_norm_citation'),
        ('offers', '0004_passage_origin_vision'),
        ('portal', '0003_garantias'),
        ('tenders', '0007_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalOk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, null=True, verbose_name='renglones')),
                ('verdicts', models.JSONField(blank=True, default=dict, verbose_name='dictamen por renglón')),
                ('action', models.CharField(choices=[('dar_ok', 'Dar el ok del informe técnico'), ('retirar_ok', 'Retirar el ok')], max_length=12, verbose_name='acción')),
                ('note', models.TextField(blank=True, verbose_name='nota')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
            ],
            options={
                'verbose_name': 'ok del informe técnico',
                'verbose_name_plural': 'oks del informe técnico',
                'db_table': 'assessment_technical_ok',
            },
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='assessment_citation_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='assessment_citation_oferta_fields',
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='assessment_citation_pliego_fields',
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='assessment_citation_norma_fields',
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='assessment_citation_respuesta_fields',
        ),
        migrations.RemoveConstraint(
            model_name='result',
            name='assessment_result_doubt_valid',
        ),
        migrations.AddField(
            model_name='citation',
            name='portal_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_citations', to='portal.portalitem', verbose_name='ítem del Portal'),
        ),
        migrations.AddField(
            model_name='citation',
            name='portal_kind',
            field=models.CharField(blank=True, choices=[('garantia', 'Garantía'), ('cotizacion', 'Cotización'), ('total', 'Total'), ('cuit', 'CUIT')], max_length=12, verbose_name='dato del Portal'),
        ),
        migrations.AddField(
            model_name='result',
            name='facts',
            field=models.JSONField(blank=True, default=dict, verbose_name='hechos verificados'),
        ),
        migrations.AddField(
            model_name='result',
            name='opinion',
            field=models.CharField(blank=True, choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('no_determinado', 'No determinado')], max_length=15, verbose_name='opinión del sistema'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='kind',
            field=models.CharField(choices=[('oferta', 'Texto de la oferta'), ('pliego', 'Texto del pliego'), ('norma', 'Norma'), ('respuesta', 'Respuesta de la Comisión'), ('portal', 'Dato del Portal')], max_length=10, verbose_name='clase'),
        ),
        migrations.AlterField(
            model_name='result',
            name='doubt',
            field=models.CharField(blank=True, choices=[('duda', 'Duda'), ('sin_corroborar', 'Sin corroborar'), ('contradiccion', 'Contradicción entre documentos'), ('lectura_incompleta', 'Lectura incompleta'), ('externo', 'Falta la hoja de compliance'), ('sin_cita', 'Sin cita ubicada'), ('sin_dato', 'Falta un dato'), ('pendiente_informe_tecnico', 'Pendiente del informe técnico'), ('no_se_pudo_leer', 'No se pudo leer'), ('en_portal', 'El documento está en el Portal'), ('falta_coincidencia', 'Falta de coincidencia con el Portal')], max_length=30, verbose_name='motivo de la duda'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['oferta', 'pliego', 'norma', 'respuesta', 'portal'])), name='assessment_citation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'oferta'), _negated=True), models.Q(('kind', 'oferta'), ('document__isnull', False), ('reading__isnull', False), ('page__isnull', False), ('char_start__isnull', False), ('char_end__isnull', False), ('requirement_quote__isnull', True), ('norm_unit__isnull', True), ('answer__isnull', True), ('portal_item__isnull', True), ('char_end__gte', models.F('char_start')), models.Q(('text', ''), _negated=True), ('portal_kind', '')), _connector='OR'), name='assessment_citation_oferta_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'pliego'), _negated=True), models.Q(('kind', 'pliego'), ('requirement_quote__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('norm_unit__isnull', True), ('answer__isnull', True), ('portal_item__isnull', True), models.Q(('text', ''), _negated=True), ('portal_kind', '')), _connector='OR'), name='assessment_citation_pliego_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'norma'), _negated=True), models.Q(('kind', 'norma'), ('norm_unit__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('requirement_quote__isnull', True), ('answer__isnull', True), ('portal_item__isnull', True), models.Q(('text', ''), _negated=True), models.Q(('label', ''), _negated=True), ('portal_kind', '')), _connector='OR'), name='assessment_citation_norma_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'respuesta'), _negated=True), models.Q(('kind', 'respuesta'), ('answer__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('requirement_quote__isnull', True), ('norm_unit__isnull', True), ('portal_item__isnull', True), ('portal_kind', '')), _connector='OR'), name='assessment_citation_respuesta_fields'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'portal'), _negated=True), models.Q(('kind', 'portal'), ('portal_item__isnull', False), ('document__isnull', True), ('reading__isnull', True), ('page__isnull', True), ('char_start__isnull', True), ('char_end__isnull', True), ('requirement_quote__isnull', True), ('norm_unit__isnull', True), ('answer__isnull', True), models.Q(('text', ''), _negated=True), ('portal_kind__in', ['garantia', 'cotizacion', 'total', 'cuit'])), _connector='OR'), name='assessment_citation_portal_fields'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('doubt__in', ['duda', 'sin_corroborar', 'contradiccion', 'lectura_incompleta', 'externo', 'sin_cita', 'sin_dato', 'pendiente_informe_tecnico', 'no_se_pudo_leer', 'en_portal', 'falta_coincidencia']), ('doubt', ''), _connector='OR'), name='assessment_result_doubt_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('opinion__in', ['cumple', 'no_cumple', 'no_determinado']), ('opinion', ''), _connector='OR'), name='assessment_result_opinion_valid'),
        ),
        migrations.AddField(
            model_name='technicalok',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_technical_oks', to='audit.auditevent', verbose_name='hecho registrado'),
        ),
        migrations.AddField(
            model_name='technicalok',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_technical_oks', to='offers.offer', verbose_name='oferta'),
        ),
        migrations.AddField(
            model_name='technicalok',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_technical_oks', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddConstraint(
            model_name='technicalok',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['dar_ok', 'retirar_ok'])), name='assessment_technical_ok_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='technicalok',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'retirar_ok'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='assessment_technical_ok_note_required'),
        ),
    ]
