# Generated by Django 6.1.1 on 2026-10-03 01:44

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_append_only'),
        ('norms', '0001_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default='cuerpo', max_length=30, verbose_name='parte')),
                ('publication_date', models.DateField(verbose_name='fecha de publicación')),
                ('effective_from', models.DateField(verbose_name='vigente desde')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('source', models.TextField(verbose_name='fuente')),
                ('version_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de versión')),
                ('in_use', models.BooleanField(default=False, verbose_name='en uso')),
                ('same_norm_confirmation', models.CharField(blank=True, choices=[('other_file', 'Otro archivo de la misma norma'), ('new_version', 'Versión nueva')], max_length=20, verbose_name='confirmación de misma norma')),
                ('file_name', models.CharField(max_length=255, verbose_name='nombre del archivo')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'Página web')], max_length=10, verbose_name='formato')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='tamaño')),
                ('file_sha256', models.CharField(max_length=64, unique=True, verbose_name='huella del archivo')),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cargado')),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_loaded', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'norms_document',
            },
        ),
        migrations.CreateModel(
            name='CorpusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creada')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_corpus_version', to='audit.auditevent', verbose_name='hecho que la originó')),
            ],
            options={
                'verbose_name': 'versión de la normativa',
                'verbose_name_plural': 'versiones de la normativa',
                'db_table': 'norms_corpus_version',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='file', serialize=False, to='norms.document', verbose_name='documento')),
                ('content', models.BinaryField(verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'archivo original',
                'verbose_name_plural': 'archivos originales',
                'db_table': 'norms_document_file',
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('regimen_especifico', 'Régimen específico'), ('otra_normativa', 'Otra normativa aplicable'), ('marco_nacional', 'Marco nacional'), ('dictamen_legal', 'Dictamen legal'), ('recomendacion_auditoria', 'Recomendación de auditoría')], max_length=30, verbose_name='categoría')),
                ('norm_type', models.CharField(max_length=50, verbose_name='tipo')),
                ('number', models.CharField(max_length=30, verbose_name='número')),
                ('year', models.PositiveSmallIntegerField(verbose_name='año')),
                ('issuer', models.CharField(max_length=200, verbose_name='organismo emisor')),
                ('title', models.TextField(verbose_name='título')),
                ('general_regime', models.BooleanField(default=False, verbose_name='régimen general')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norms_created', to=settings.AUTH_USER_MODEL, verbose_name='dada de alta por')),
            ],
            options={
                'verbose_name': 'norma',
                'verbose_name_plural': 'normas',
                'db_table': 'norms_norm',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='norms.norm', verbose_name='norma'),
        ),
        migrations.CreateModel(
            name='PendingAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_type', models.CharField(max_length=50, verbose_name='tipo')),
                ('number', models.CharField(max_length=30, verbose_name='número')),
                ('year', models.PositiveSmallIntegerField(verbose_name='año')),
                ('issuer', models.CharField(max_length=200, verbose_name='organismo emisor')),
                ('source_ref', models.TextField(verbose_name='referencia en la fuente')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='anotada')),
                ('loaded_norm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendment_entries', to='norms.norm', verbose_name='norma cargada')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_amendments_registered', to=settings.AUTH_USER_MODEL, verbose_name='anotada por')),
                ('target_norm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_amendments', to='norms.norm', verbose_name='norma alcanzada')),
            ],
            options={
                'verbose_name': 'modificatoria sin cargar',
                'verbose_name_plural': 'modificatorias sin cargar',
                'db_table': 'norms_pending_amendment',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='número de lectura')),
                ('status', models.CharField(choices=[('pending', 'Leída, sin validar'), ('validated', 'Validada'), ('superseded', 'Reemplazada')], default='pending', max_length=20, verbose_name='estado')),
                ('pages', models.JSONField(verbose_name='lectura')),
                ('canonical_text', models.TextField(verbose_name='texto canónico')),
                ('canonical_sha256', models.CharField(max_length=64, verbose_name='huella del texto canónico')),
                ('tool_versions', models.JSONField(verbose_name='versiones de las herramientas')),
                ('report', models.JSONField(verbose_name='informe')),
                ('report_text', models.TextField(verbose_name='informe legible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='leída')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validada')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='reemplazada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings_created', to=settings.AUTH_USER_MODEL, verbose_name='leída por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='norms.document', verbose_name='documento')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readings_validated', to=settings.AUTH_USER_MODEL, verbose_name='validada por')),
            ],
            options={
                'verbose_name': 'lectura',
                'verbose_name_plural': 'lecturas',
                'db_table': 'norms_reading',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('modifica', 'Modifica'), ('complementa', 'Complementa'), ('reglamenta', 'Reglamenta'), ('deroga', 'Deroga')], max_length=20, verbose_name='tipo de relación')),
                ('source_unit_key', models.CharField(blank=True, max_length=255, verbose_name='unidad de origen')),
                ('target_unit_key', models.CharField(blank=True, max_length=255, verbose_name='unidad alcanzada')),
                ('effective_date', models.DateField(verbose_name='vigente desde')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrada')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_registered', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('source_norm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_from', to='norms.norm', verbose_name='norma de origen')),
                ('target_norm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_to', to='norms.norm', verbose_name='norma alcanzada')),
            ],
            options={
                'verbose_name': 'relación',
                'verbose_name_plural': 'relaciones',
                'db_table': 'norms_relation',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('articulo', 'Artículo'), ('inciso', 'Inciso'), ('anexo', 'Anexo'), ('considerando', 'Considerando'), ('clausula', 'Cláusula'), ('punto', 'Punto'), ('parrafo', 'Párrafo')], max_length=20, verbose_name='tipo')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='número')),
                ('label', models.TextField(verbose_name='etiqueta')),
                ('key', models.CharField(max_length=255, verbose_name='clave')),
                ('path', models.TextField(verbose_name='ruta')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='página inicial')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='página final')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(verbose_name='texto literal')),
                ('text_origin', models.CharField(choices=[('pdf_text', 'PDF con texto'), ('ocr', 'Reconocimiento de texto'), ('web', 'Página web')], max_length=10, verbose_name='origen del texto')),
                ('ocr_confidence_min', models.FloatField(blank=True, null=True, verbose_name='confianza mínima')),
                ('ocr_confidence_avg', models.FloatField(blank=True, null=True, verbose_name='confianza promedio')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='norms.unit', verbose_name='contenida en')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='norms.reading', verbose_name='lectura')),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
                'db_table': 'norms_unit',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto de la unidad')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto de la unidad')),
                ('header', models.TextField(verbose_name='encabezado de contexto')),
                ('text', models.TextField(verbose_name='texto')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, verbose_name='vector')),
                ('embedding_model', models.CharField(max_length=200, verbose_name='modelo de embeddings')),
                ('embedding_revision', models.CharField(max_length=64, verbose_name='huella del modelo')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='norms.unit', verbose_name='unidad')),
            ],
            options={
                'verbose_name': 'pasaje',
                'verbose_name_plural': 'pasajes',
                'db_table': 'norms_passage',
            },
        ),
        migrations.AddConstraint(
            model_name='norm',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['regimen_especifico', 'otra_normativa', 'marco_nacional', 'dictamen_legal', 'recomendacion_auditoria'])), name='norms_norm_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='norm',
            constraint=models.UniqueConstraint(fields=('norm_type', 'number', 'year', 'issuer'), name='norms_norm_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='norm',
            constraint=models.CheckConstraint(condition=models.Q(('general_regime', False), ('category', 'regimen_especifico'), _connector='OR'), name='norms_norm_general_regime_only_specific'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('part', 'cuerpo'), ('part__regex', '^anexo(-[a-z0-9]+)?$'), _connector='OR'), name='norms_document_part_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('same_norm_confirmation', ''), ('same_norm_confirmation__in', ['other_file', 'new_version']), _connector='OR'), name='norms_document_same_norm_confirmation_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_format__in', ['pdf', 'html'])), name='norms_document_file_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_sha256__regex', '^[0-9a-f]{64}$')), name='norms_document_file_sha256_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('in_use', False), ('version_number__isnull', False), _connector='OR'), name='norms_document_in_use_has_version'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('in_use', True)), fields=('norm', 'part', 'version_number'), name='norms_document_one_in_use_per_part_version'),
        ),
        migrations.AddConstraint(
            model_name='pendingamendment',
            constraint=models.UniqueConstraint(fields=('target_norm', 'norm_type', 'number', 'year', 'issuer'), name='norms_pending_amendment_unique_in_target'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'validated', 'superseded'])), name='norms_reading_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='norms_reading_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.CheckConstraint(condition=models.Q(('relation_type__in', ['modifica', 'complementa', 'reglamenta', 'deroga'])), name='norms_relation_relation_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('unit_type__in', ['articulo', 'inciso', 'anexo', 'considerando', 'clausula', 'punto', 'parrafo'])), name='norms_unit_unit_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('text_origin__in', ['pdf_text', 'ocr', 'web'])), name='norms_unit_text_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='norms_unit_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('reading', 'key'), name='norms_unit_key_unique_in_reading'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='norms_passage_order_unique_in_unit'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='norms_passage_char_range_valid'),
        ),
    ]
