# Generated by Django 6.1.1 on 2026-10-03 02:05
"""Columna `tsv` de `norms_passage` y su índice GIN (plan 001, "Modelo de datos" y
"Búsqueda por palabras: tildes, singular y plural"; ADR-0007).

`tsv` es una columna calculada por la base, `GENERATED ALWAYS AS
(search_document(text)) STORED`: se calcula al insertar o modificar un pasaje. El campo
lo generó `makemigrations`; el índice GIN va con SQL propio porque `GinIndex` exige
`django.contrib.postgres`, que no está instalada.
"""

import evaluon.norms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0003_search_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='tsv',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('text'), function='search_document', output_field=evaluon.norms.models.TsvectorField()), output_field=evaluon.norms.models.TsvectorField(), verbose_name='vector de búsqueda por palabras'),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX norms_passage_tsv_gin ON norms_passage USING gin (tsv);",
            reverse_sql="DROP INDEX IF EXISTS norms_passage_tsv_gin;",
        ),
    ]
