# Generated by Django 6.1.1 on 2026-10-05 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0003_docx_format'),
        ('tenders', '0006_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploration', models.PositiveIntegerField(verbose_name='exploración')),
                ('url', models.CharField(max_length=2000, verbose_name='dirección')),
                ('file_name', models.CharField(max_length=300, verbose_name='nombre del archivo')),
                ('file_format', models.CharField(blank=True, max_length=20, verbose_name='formato')),
                ('sha256', models.CharField(max_length=64, verbose_name='huella')),
                ('content', models.BinaryField(verbose_name='contenido')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='consultado')),
            ],
            options={
                'verbose_name': 'archivo del Portal',
                'verbose_name_plural': 'archivos del Portal',
                'db_table': 'portal_file',
            },
        ),
        migrations.CreateModel(
            name='PortalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('procedimiento', 'Procedimiento'), ('renglones', 'Renglones'), ('documento', 'Documento'), ('oferta', 'Oferta')], max_length=15, verbose_name='tipo')),
                ('key', models.CharField(max_length=300, verbose_name='clave')),
                ('payload', models.JSONField(verbose_name='datos propuestos')),
                ('content_sha256', models.CharField(max_length=64, verbose_name='huella del contenido')),
                ('damaged_fields', models.JSONField(default=list, verbose_name='campos con texto dañado')),
                ('state', models.CharField(choices=[('propuesto', 'Propuesto'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cargado', 'Cargado'), ('fallido', 'Fallido')], default='propuesto', max_length=10, verbose_name='estado')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido')),
                ('loaded_model', models.CharField(blank=True, max_length=20, verbose_name='objeto creado o asociado')),
                ('loaded_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='id del objeto')),
                ('failure', models.TextField(blank=True, verbose_name='motivo de la falla')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_items_decided', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='portal.portalfile', verbose_name='archivo')),
            ],
            options={
                'verbose_name': 'ítem de la propuesta',
                'verbose_name_plural': 'ítems de la propuesta',
                'db_table': 'portal_item',
            },
        ),
        migrations.CreateModel(
            name='PortalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('description', models.TextField(verbose_name='descripción')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='cantidad')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='unidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='portal.portalitem', verbose_name='ítem de origen')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_lines', to='tenders.procedure', verbose_name='procedimiento')),
            ],
            options={
                'verbose_name': 'renglón del Portal',
                'verbose_name_plural': 'renglones del Portal',
                'db_table': 'portal_line',
                'ordering': ['procedure_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PortalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True, verbose_name='enlace')),
                ('process_number', models.CharField(blank=True, max_length=100, verbose_name='número del proceso')),
                ('following', models.BooleanField(default=True, verbose_name='se sigue revisando')),
                ('last_review_on', models.DateField(blank=True, null=True, verbose_name='última revisión')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_links_created', to=settings.AUTH_USER_MODEL, verbose_name='alta por')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_links', to='tenders.procedure', verbose_name='procedimiento')),
            ],
            options={
                'verbose_name': 'enlace del Portal',
                'verbose_name_plural': 'enlaces del Portal',
                'db_table': 'portal_link',
            },
        ),
        migrations.AddField(
            model_name='portalfile',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='portal.portallink', verbose_name='enlace'),
        ),
        migrations.CreateModel(
            name='PortalOfferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=13, verbose_name='CUIT')),
                ('confirmed_on', models.DateField(blank=True, null=True, verbose_name='confirmada el')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='moneda')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='total')),
                ('guarantee_type', models.CharField(blank=True, max_length=100, verbose_name='tipo de garantía')),
                ('guarantee_form', models.CharField(blank=True, max_length=100, verbose_name='forma de garantía')),
                ('guarantee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='monto de la garantía')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_data', to='portal.portalitem', verbose_name='ítem de origen')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_data', to='offers.offer', verbose_name='oferta')),
            ],
            options={
                'verbose_name': 'datos de la oferta del Portal',
                'verbose_name_plural': 'datos de la oferta del Portal',
                'db_table': 'portal_offer_data',
            },
        ),
        migrations.CreateModel(
            name='PortalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploration', models.PositiveIntegerField(verbose_name='exploración')),
                ('kind', models.CharField(choices=[('proceso', 'Página del proceso'), ('acta', 'Acta de apertura'), ('dictamen', 'Dictamen'), ('cuadro', 'Cuadro comparativo')], max_length=10, verbose_name='tipo')),
                ('url', models.CharField(max_length=2000, verbose_name='dirección')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='consultada')),
                ('sha256', models.CharField(max_length=64, verbose_name='huella')),
                ('content', models.BinaryField(verbose_name='contenido')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='portal.portallink', verbose_name='enlace')),
            ],
            options={
                'verbose_name': 'página del Portal',
                'verbose_name_plural': 'páginas del Portal',
                'db_table': 'portal_page',
            },
        ),
        migrations.AddField(
            model_name='portalitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='portal.portalpage', verbose_name='página de origen'),
        ),
        migrations.AddField(
            model_name='portalfile',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='portal.portalpage', verbose_name='página de origen'),
        ),
        migrations.CreateModel(
            name='PortalProcedureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=100, verbose_name='expediente')),
                ('legal_framework', models.CharField(blank=True, max_length=500, verbose_name='encuadre legal')),
                ('schedule', models.JSONField(default=list, verbose_name='cronograma')),
                ('guarantees', models.JSONField(default=list, verbose_name='garantías')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_data', to='portal.portalitem', verbose_name='ítem de origen')),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_data', to='tenders.procedure', verbose_name='procedimiento')),
            ],
            options={
                'verbose_name': 'datos del procedimiento del Portal',
                'verbose_name_plural': 'datos del procedimiento del Portal',
                'db_table': 'portal_procedure_data',
            },
        ),
        migrations.CreateModel(
            name='PortalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exploration', models.PositiveIntegerField(verbose_name='exploración')),
                ('origin', models.CharField(choices=[('importacion', 'Importación'), ('revision', 'Revisión periódica')], max_length=12, verbose_name='origen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creada')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_proposals', to='tenders.job', verbose_name='pedido')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='portal.portallink', verbose_name='enlace')),
            ],
            options={
                'verbose_name': 'propuesta del Portal',
                'verbose_name_plural': 'propuestas del Portal',
                'db_table': 'portal_proposal',
            },
        ),
        migrations.AddField(
            model_name='portalitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='portal.portalproposal', verbose_name='propuesta'),
        ),
        migrations.CreateModel(
            name='PortalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='precio')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='cantidad')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='portal.portalline', verbose_name='renglón')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_quotes', to='offers.offer', verbose_name='oferta')),
            ],
            options={
                'verbose_name': 'cotización del Portal',
                'verbose_name_plural': 'cotizaciones del Portal',
                'db_table': 'portal_quote',
            },
        ),
        migrations.AddConstraint(
            model_name='portalline',
            constraint=models.UniqueConstraint(fields=('procedure', 'number'), name='portal_line_number_unique'),
        ),
        migrations.AddIndex(
            model_name='portalpage',
            index=models.Index(fields=['link', 'exploration'], name='portal_page_link_expl'),
        ),
        migrations.AddConstraint(
            model_name='portalpage',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['proceso', 'acta', 'dictamen', 'cuadro'])), name='portal_page_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalpage',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='portal_page_sha256_valid'),
        ),
        migrations.AddIndex(
            model_name='portalfile',
            index=models.Index(fields=['link', 'exploration'], name='portal_file_link_expl'),
        ),
        migrations.AddConstraint(
            model_name='portalfile',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='portal_file_sha256_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalproposal',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['importacion', 'revision'])), name='portal_proposal_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalproposal',
            constraint=models.UniqueConstraint(fields=('link', 'exploration', 'origin'), name='portal_proposal_unique'),
        ),
        migrations.AddIndex(
            model_name='portalitem',
            index=models.Index(fields=['key', 'kind'], name='portal_item_key_kind'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['procedimiento', 'renglones', 'documento', 'oferta'])), name='portal_item_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['propuesto', 'aprobado', 'rechazado', 'cargado', 'fallido'])), name='portal_item_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.CheckConstraint(condition=models.Q(('content_sha256__regex', '^[0-9a-f]{64}$')), name='portal_item_sha256_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.UniqueConstraint(fields=('proposal', 'key'), name='portal_item_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'propuesto'), models.Q(('decided_by__isnull', False), ('decided_at__isnull', False)), _connector='OR'), name='portal_item_decision_has_author'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'cargado'), _negated=True), models.Q(models.Q(('loaded_model', ''), _negated=True), ('loaded_id__isnull', False)), _connector='OR'), name='portal_item_loaded_has_object'),
        ),
        migrations.AddConstraint(
            model_name='portalitem',
            constraint=models.CheckConstraint(condition=models.Q(('loaded_model', ''), ('loaded_model__in', ['tenders_procedure', 'tenders_document', 'offers_offer']), _connector='OR'), name='portal_item_loaded_model_valid'),
        ),
        migrations.AddConstraint(
            model_name='portalquote',
            constraint=models.UniqueConstraint(fields=('offer', 'line'), name='portal_quote_unique'),
        ),
    ]
