# Generated by Django 6.1.1 on 2026-10-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_role',
            field=models.CharField(blank=True, choices=[('', 'Ninguno'), ('operator', 'Operador'), ('evaluator', 'Evaluador')], default='', max_length=10, verbose_name='rol de la Comisión'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('commission_role__in', ['', 'operator', 'evaluator'])), name='accounts_user_commission_role_valid'),
        ),
    ]
