# Generated by Django 6.1.1 on 2026-10-03 02:32

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='consultada')),
                ('question', models.TextField(verbose_name='pregunta')),
                ('reference_date', models.DateField(verbose_name='fecha de autorización del procedimiento')),
                ('corpus_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='versión de la normativa')),
                ('status', models.CharField(choices=[('grounded', 'Con fundamento'), ('undetermined', 'No determinado'), ('error', 'Falla técnica')], max_length=20, verbose_name='resultado')),
                ('reason', models.CharField(blank=True, choices=[('no_regime_at_date', 'Sin régimen a la fecha'), ('below_threshold', 'Nada pertinente'), ('model_abstained', 'El modelo se abstuvo'), ('invalid_citation', 'Cita inválida'), ('timeout', 'Espera agotada'), ('service_unavailable', 'Servicio que no responde'), ('invalid_output', 'Salida inválida'), ('input_too_long', 'Pedido que no entra en el contexto')], max_length=30, verbose_name='motivo')),
                ('parameters', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='parámetros')),
                ('candidates', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='candidatos')),
                ('selected', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='unidades seleccionadas')),
                ('max_score', models.FloatField(blank=True, null=True, verbose_name='puntaje más alto')),
                ('prompt_version', models.CharField(blank=True, max_length=50, verbose_name='versión de las instrucciones')),
                ('request', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='pedido')),
                ('raw_output', models.TextField(blank=True, verbose_name='salida sin tocar')),
                ('result', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='resultado guardado')),
                ('anomalies', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='anomalías')),
                ('timings', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='tiempos')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='query', to='audit.auditevent', verbose_name='hecho registrado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'db_table': 'queries_query',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['grounded', 'undetermined', 'error'])), name='queries_query_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('reason', ''), ('status', 'grounded')), models.Q(('reason__in', ['no_regime_at_date', 'below_threshold', 'model_abstained', 'invalid_citation']), ('status', 'undetermined')), models.Q(('reason__in', ['timeout', 'service_unavailable', 'invalid_output', 'input_too_long']), ('status', 'error')), _connector='OR'), name='queries_query_reason_matches_status'), models.CheckConstraint(condition=models.Q(('max_score__isnull', True), models.Q(('max_score__gte', 0), ('max_score__lte', 1)), _connector='OR'), name='queries_query_max_score_range')],
            },
        ),
    ]
