# Generated by Django 6.1.1 on 2026-10-05 12:41

import django.db.models.deletion
import django.utils.timezone
import evaluon.norms.models
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0005_ofertas'),
        ('tenders', '0005_ofertas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('economica', 'Propuesta económica'), ('tecnica', 'Documentación técnica'), ('garantia', 'Garantía'), ('otro', 'Otro')], max_length=20, verbose_name='tipo')),
                ('title', models.TextField(verbose_name='título')),
                ('file_name', models.CharField(max_length=255, verbose_name='nombre del archivo')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'Foto JPG'), ('png', 'Foto PNG')], max_length=10, verbose_name='formato')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='tamaño')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='huella del archivo')),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cargado')),
                ('loaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_documents_loaded', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
            ],
            options={
                'verbose_name': 'documento de la oferta',
                'verbose_name_plural': 'documentos de las ofertas',
                'db_table': 'offers_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='file', serialize=False, to='offers.document', verbose_name='documento')),
                ('content', models.BinaryField(verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'archivo original de la oferta',
                'verbose_name_plural': 'archivos originales de las ofertas',
                'db_table': 'offers_document_file',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('bidder', models.CharField(max_length=300, verbose_name='oferente')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_created', to=settings.AUTH_USER_MODEL, verbose_name='dada de alta por')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='tenders.procedure', verbose_name='procedimiento')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'db_table': 'offers_offer',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='offers.offer', verbose_name='oferta'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='número de lectura')),
                ('pages', models.JSONField(verbose_name='lectura')),
                ('canonical_text', models.TextField(verbose_name='texto canónico')),
                ('canonical_sha256', models.CharField(max_length=64, verbose_name='huella del texto canónico')),
                ('tool_versions', models.JSONField(verbose_name='versiones de las herramientas')),
                ('report', models.JSONField(verbose_name='informe')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='leída')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='offers.document', verbose_name='documento')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_readings', to='tenders.job', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'lectura de la oferta',
                'verbose_name_plural': 'lecturas de las ofertas',
                'db_table': 'offers_reading',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('key', models.CharField(max_length=40, verbose_name='clave')),
                ('page', models.PositiveIntegerField(verbose_name='página')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(verbose_name='texto literal')),
                ('text_origin', models.CharField(choices=[('pdf_text', 'PDF con texto'), ('ocr', 'Reconocimiento de texto'), ('web', 'Página web')], max_length=10, verbose_name='origen del texto')),
                ('ocr_confidence_min', models.FloatField(blank=True, null=True, verbose_name='confianza mínima')),
                ('ocr_confidence_avg', models.FloatField(blank=True, null=True, verbose_name='confianza promedio')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, verbose_name='vector')),
                ('tsv', models.GeneratedField(db_persist=True, expression=models.Func(models.F('text'), function='search_document', output_field=evaluon.norms.models.TsvectorField()), output_field=evaluon.norms.models.TsvectorField(), verbose_name='vector de búsqueda por palabras')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='offers.reading', verbose_name='lectura')),
            ],
            options={
                'verbose_name': 'pasaje de la oferta',
                'verbose_name_plural': 'pasajes de las ofertas',
                'db_table': 'offers_passage',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('channel', models.CharField(choices=[('screen', 'Pantalla'), ('eval', 'Evaluación')], max_length=10, verbose_name='canal')),
                ('readings', models.JSONField(verbose_name='lecturas usadas')),
                ('models_used', models.JSONField(db_column='models', verbose_name='modelos')),
                ('parameters', models.JSONField(verbose_name='parámetros')),
                ('prompt_versions', models.JSONField(verbose_name='versiones de las instrucciones')),
                ('counts', models.JSONField(default=dict, verbose_name='cuentas')),
                ('timings', models.JSONField(default=dict, verbose_name='tiempos')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('technical_documents', models.JSONField(default=dict, verbose_name='documentación técnica')),
                ('built_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='armada')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_sheets', to='tenders.job', verbose_name='pedido')),
                ('matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_sheets', to='tenders.matrixversion', verbose_name='versión de la matriz')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheets', to='offers.offer', verbose_name='oferta')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheets_requested', to=settings.AUTH_USER_MODEL, verbose_name='pedida por')),
            ],
            options={
                'verbose_name': 'ficha',
                'verbose_name_plural': 'fichas',
                'db_table': 'offers_sheet',
            },
        ),
        migrations.CreateModel(
            name='SheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('encontrado', 'Encontrado'), ('no_encontrado', 'No se encontró en la oferta')], max_length=20, verbose_name='resultado')),
                ('synthesis', models.TextField(blank=True, verbose_name='síntesis')),
                ('quoted', models.CharField(blank=True, choices=[('cotizado', 'Cotizado'), ('no_cotizado', 'No cotizado'), ('no_se_pudo_leer', 'No se pudo leer')], max_length=20, verbose_name='cotización')),
                ('unread_pages_warning', models.BooleanField(default=False, verbose_name='hay páginas sin leer')),
                ('state', models.CharField(choices=[('propuesto', 'Propuesto'), ('confirmado', 'Confirmado')], default='propuesto', max_length=20, verbose_name='estado')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_entries', to='tenders.requirement', verbose_name='requisito')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='offers.sheet', verbose_name='ficha')),
            ],
            options={
                'verbose_name': 'fila de la ficha',
                'verbose_name_plural': 'filas de las fichas',
                'db_table': 'offers_sheet_entry',
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('char_start', models.PositiveIntegerField(verbose_name='inicio en el texto canónico')),
                ('char_end', models.PositiveIntegerField(verbose_name='fin en el texto canónico')),
                ('text', models.TextField(verbose_name='texto literal')),
                ('origin', models.CharField(choices=[('sistema', 'Propuesto por el sistema'), ('persona', 'Agregado por una persona')], max_length=10, verbose_name='origen')),
                ('state', models.CharField(choices=[('propuesto', 'Propuesto'), ('confirmado', 'Confirmado'), ('quitado', 'Quitado')], default='propuesto', max_length=20, verbose_name='estado')),
                ('proposed', models.JSONField(default=dict, verbose_name='propuesto')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragments', to='offers.passage', verbose_name='pasaje')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragments', to='offers.sheetentry', verbose_name='fila')),
            ],
            options={
                'verbose_name': 'fragmento',
                'verbose_name_plural': 'fragmentos',
                'db_table': 'offers_fragment',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirmar', 'Confirmar'), ('corregir', 'Corregir'), ('quitar', 'Quitar'), ('restituir', 'Restituir'), ('agregar', 'Agregar')], max_length=20, verbose_name='acción')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='antes')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='después')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='momento')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_changes', to='audit.auditevent', verbose_name='hecho registrado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_changes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='offers.fragment', verbose_name='fragmento')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='offers.sheetentry', verbose_name='fila')),
            ],
            options={
                'verbose_name': 'cambio de la ficha',
                'verbose_name_plural': 'cambios de las fichas',
                'db_table': 'offers_change',
            },
        ),
        migrations.CreateModel(
            name='SheetStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidates', models.JSONField(verbose_name='candidatos')),
                ('request', models.JSONField(blank=True, null=True, verbose_name='pedido')),
                ('raw_output', models.TextField(blank=True, verbose_name='salida cruda')),
                ('parsed', models.JSONField(blank=True, null=True, verbose_name='interpretado')),
                ('anomalies', models.JSONField(default=list, verbose_name='anomalías')),
                ('timings', models.JSONField(default=dict, verbose_name='tiempos')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='offers.sheetentry', verbose_name='fila')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='offers.sheetstep', verbose_name='reintento de')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='offers.sheet', verbose_name='ficha')),
            ],
            options={
                'verbose_name': 'pedido al modelo de la ficha',
                'verbose_name_plural': 'pedidos al modelo de las fichas',
                'db_table': 'offers_sheet_step',
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('procedure', 'number'), name='offers_offer_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('procedure', 'bidder'), name='offers_offer_bidder_unique'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['economica', 'tecnica', 'garantia', 'otro']), ('kind', ''), _connector='OR'), name='offers_document_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_format__in', ['pdf', 'jpg', 'png'])), name='offers_document_file_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_sha256__regex', '^[0-9a-f]{64}$')), name='offers_document_file_sha256_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('offer', 'file_sha256'), name='offers_document_sha256_unique_in_offer'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='offers_reading_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.CheckConstraint(condition=models.Q(('text_origin__in', ['pdf_text', 'ocr', 'web'])), name='offers_passage_text_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='offers_passage_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('reading', 'key'), name='offers_passage_key_unique_in_reading'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('reading', 'order'), name='offers_passage_order_unique_in_reading'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['screen', 'eval'])), name='offers_sheet_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(fields=('offer', 'number'), name='offers_sheet_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='sheetentry',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['encontrado', 'no_encontrado'])), name='offers_sheet_entry_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='sheetentry',
            constraint=models.CheckConstraint(condition=models.Q(('quoted__in', ['cotizado', 'no_cotizado', 'no_se_pudo_leer']), ('quoted', ''), _connector='OR'), name='offers_sheet_entry_quoted_valid'),
        ),
        migrations.AddConstraint(
            model_name='sheetentry',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['propuesto', 'confirmado'])), name='offers_sheet_entry_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='sheetentry',
            constraint=models.UniqueConstraint(fields=('sheet', 'requirement'), name='offers_sheet_entry_requirement_unique'),
        ),
        migrations.AddConstraint(
            model_name='fragment',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['sistema', 'persona'])), name='offers_fragment_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='fragment',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['propuesto', 'confirmado', 'quitado'])), name='offers_fragment_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='fragment',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gte', models.F('char_start'))), name='offers_fragment_char_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='fragment',
            constraint=models.UniqueConstraint(fields=('entry', 'order'), name='offers_fragment_order_unique_in_entry'),
        ),
        migrations.AddConstraint(
            model_name='change',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['confirmar', 'corregir', 'quitar', 'restituir', 'agregar'])), name='offers_change_action_valid'),
        ),
    ]
