# Generated by Django 6.1.1 on 2026-10-05 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='offers_document_file_format_valid',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'Foto JPG'), ('png', 'Foto PNG'), ('docx', 'Word')], max_length=10, verbose_name='formato'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_format__in', ['pdf', 'jpg', 'png', 'docx'])), name='offers_document_file_format_valid'),
        ),
    ]
