# Cambio de opciones (T-189; REQ-073): el tipo de un documento de la oferta suma `compliance`, la
# hoja de compliance que la Comisión sube una vez por oferta.

# Generated by Django 6.1.1 on 2026-10-07 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_passage_origin_vision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='offers_document_kind_valid',
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(blank=True, choices=[('economica', 'Propuesta económica'), ('tecnica', 'Documentación técnica'), ('garantia', 'Garantía'), ('compliance', 'Hoja de compliance'), ('otro', 'Otro')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['economica', 'tecnica', 'garantia', 'compliance', 'otro']), ('kind', ''), _connector='OR'), name='offers_document_kind_valid'),
        ),
    ]
